import eslintConfigNext from "eslint-config-next";
import simpleImportSort from "eslint-plugin-simple-import-sort";
import unusedImports from "eslint-plugin-unused-imports";

const config = [
  {
    // Agent worktrees under .claude/ are full checkouts of this repo, so
    // linting them re-reports every file against whatever branch they hold.
    // coverage/ is generated by `vitest --coverage`; it belongs here rather than
    // as a --ignore-pattern flag in the npm scripts, so a bare `npx eslint .`
    // and editor integrations honour it too.
    ignores: [".claude/**", ".next/**", "coverage/**"],
  },
  ...eslintConfigNext,
  {
    plugins: {
      "simple-import-sort": simpleImportSort,
      "unused-imports": unusedImports,
    },
    rules: {
      "simple-import-sort/imports": "error",
      "simple-import-sort/exports": "error",
      "import/no-duplicates": "error",
      "no-unused-vars": "off",
      "unused-imports/no-unused-imports": "error",
      "unused-imports/no-unused-vars": [
        "warn",
        {
          vars: "all",
          varsIgnorePattern: "^_",
          args: "after-used",
          argsIgnorePattern: "^_",
        },
      ],
    },
  },
  {
    // Scoped to TypeScript files because that is where eslint-config-next
    // registers the @typescript-eslint plugin; referencing the rule for .mjs
    // config files, where the plugin is absent, is a configuration error.
    files: ["**/*.ts", "**/*.tsx"],
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
    },
  },
  {
    files: ["**/*.test.tsx", "**/*.test.ts"],
    rules: {
      "@next/next/no-img-element": "off",
      // The DB and fetch doubles lean on `(db as any)` and friends throughout;
      // there are ~800 occurrences across the suites. `lint:ci` runs with
      // --max-warnings=0, so this has to be off rather than a warning. The rule
      // is enabled for production code above, which is where it buys something.
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
  {
    files: ["src/components/ui/QRCode.tsx"],
    rules: {
      "@next/next/no-img-element": "off",
    },
  },
  {
    // Verified live, not a blanket disable: unexempting this file produces two
    // real react-hooks/set-state-in-effect errors. useFragmentNavigation.ts was
    // also listed here and did not need it -- its only setState runs inside a
    // popstate handler, not in an effect body.
    files: ["src/components/profile/StreamingPreferences.tsx"],
    rules: {
      "react-hooks/set-state-in-effect": "off",
    },
  },
];

export default config;
