#!/usr/bin/env node
// Regenerates the brand asset module from the repo's own artwork.
//
// Three steps, all of them measured rather than guessed:
//   1. extract  — pull the `layer1` glyph group out of public/logo-master.svg,
//                 carrying the <defs> it references, into brand/mark.svg
//   2. crop     — rasterise that and scan the alpha channel, so the viewBox is
//                 tight to the painted pixels INCLUDING the drop-shadow glow
//                 (the filter's own margins are asymmetric; arithmetic gets it
//                 wrong and the mark ends up floating in dead space)
//   3. emit     — base64 every mark into logo-data.ts with its real aspect ratio
//
// Run it whenever public/*.svg or src/app/icon192.png changes:
//
//   ln -sfn ../.ds-sync/node_modules .design-sync/node_modules   # once per clone
//   node .design-sync/brand/regenerate.mjs
//
// The symlink is how the bare `playwright` import resolves; it is gitignored,
// so recreating it is part of fresh-clone setup.
import { readFileSync, writeFileSync, unlinkSync } from "node:fs";
import { pathToFileURL } from "node:url";
import { chromium } from "playwright";

const REPO = new URL("../../", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1");
const at = (p) => new URL(p, new URL("../../", import.meta.url)).pathname.replace(/^\/([A-Za-z]:)/, "$1");

const SRC = at("public/logo-master.svg");
const OUT_MARK = at(".design-sync/brand/mark.svg");
const OUT_DATA = at(".design-sync/brand/logo-data.ts");

// ── 1. extract ────────────────────────────────────────────────────────────
const src = readFileSync(SRC, "utf8");
const defs = src.match(/<defs[\s\S]*?<\/defs>/)[0];
const layer1 = src.match(/<g\s+id="layer1"[\s\S]*?<\/g>/)[0];
const origVB = src.match(/viewBox="([^"]+)"/)[1];
const ns = ' xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"';
const build = (vb) => `<svg${ns} viewBox="${vb}">\n${defs}\n${layer1}\n</svg>\n`;

writeFileSync(OUT_MARK, build(origVB));

// ── 2. crop to painted pixels ─────────────────────────────────────────────
const browser = await chromium.launch();
try {
  const svg0 = readFileSync(OUT_MARK, "utf8");
  const [vx, vy, vw, vh] = origVB.trim().split(/\s+/).map(Number);
  const W = 1000, H = Math.round((W * vh) / vw);
  const uri = "data:image/svg+xml;base64," + Buffer.from(svg0, "utf8").toString("base64");
  const probe = at(".design-sync/brand/.crop-probe.html");
  writeFileSync(probe, `<body style="margin:0"><img id="m" src="${uri}" width="${W}" height="${H}"></body>`);

  const page = await browser.newPage({ viewport: { width: W, height: H } });
  await page.goto(pathToFileURL(probe).href);
  await page.waitForFunction(() => {
    const i = document.getElementById("m");
    return i && i.complete && i.naturalWidth > 0;
  });
  const box = await page.evaluate(({ W, H }) => {
    const c = document.createElement("canvas");
    c.width = W; c.height = H;
    const ctx = c.getContext("2d");
    ctx.drawImage(document.getElementById("m"), 0, 0, W, H);
    const d = ctx.getImageData(0, 0, W, H).data;
    let x0 = W, y0 = H, x1 = -1, y1 = -1;
    for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) {
      if (d[(y * W + x) * 4 + 3] > 8) {
        if (x < x0) x0 = x; if (x > x1) x1 = x;
        if (y < y0) y0 = y; if (y > y1) y1 = y;
      }
    }
    return { x0, y0, x1, y1 };
  }, { W, H });
  unlinkSync(probe);

  const nx = vx + (box.x0 / W) * vw;
  const ny = vy + (box.y0 / H) * vh;
  const nw = vx + ((box.x1 + 1) / W) * vw - nx;
  const nh = vy + ((box.y1 + 1) / H) * vh - ny;
  writeFileSync(OUT_MARK, build([nx, ny, nw, nh].map((n) => n.toFixed(3)).join(" ")));
  console.log(`mark.svg viewBox → ${nw.toFixed(1)}×${nh.toFixed(1)} (ratio ${(nw / nh).toFixed(4)})`);
} finally {
  await browser.close();
}

// ── 3. emit ───────────────────────────────────────────────────────────────
const ratioOf = (file) => {
  const s = readFileSync(file, "utf8");
  const vb = s.match(/viewBox="([^"]+)"/);
  if (vb) { const [, , w, h] = vb[1].split(/\s+/).map(Number); return w / h; }
  return Number(s.match(/\bwidth="([\d.]+)/)[1]) / Number(s.match(/\bheight="([\d.]+)/)[1]);
};
const dataUri = (file, mime) =>
  `data:${mime};base64,` + readFileSync(file).toString("base64");

const MARKS = [
  ["WORDMARK", at("public/logo-master.svg"), "image/svg+xml", ratioOf(SRC)],
  ["ICON", OUT_MARK, "image/svg+xml", ratioOf(OUT_MARK)],
  ["APP_ICON", at("src/app/icon192.png"), "image/png", 1],
  ["TMDB", at("public/tmdb.svg"), "image/svg+xml", ratioOf(at("public/tmdb.svg"))],
  ["JUSTWATCH", at("public/justwatch.svg"), "image/svg+xml", ratioOf(at("public/justwatch.svg"))],
];

const head = `// GENERATED by .design-sync/brand/regenerate.mjs — do not hand-edit.
//
// Brand marks, inlined as data URIs straight from the repo's own assets so
// designs can actually place them. Rendered designs receive only the bundle
// and the styles.css import closure -- a <img src="/logo-master.svg"> would
// 404 there, which is exactly why PageHeader's default logo was broken.
//
// \`ICON\` is the standalone glyph, extracted from logo-master.svg's \`layer1\`
// group and tight-cropped to its painted pixels. It is the same mark the
// favicon and mobile app icons use, but scalable. \`APP_ICON\` is the shipped
// icon192.png artwork -- the glyph on its dark circular field, exactly as it
// appears on a home screen.
`;

const body = MARKS.map(([name, file, mime, ratio]) =>
  `/** ${file.slice(REPO.length).replace(/\\/g, "/")} — aspect ratio ${ratio.toFixed(4)} */\n` +
  `export const ${name} = "${dataUri(file, mime)}";\n` +
  `export const ${name}_RATIO = ${ratio.toFixed(4)};\n`
).join("\n");

writeFileSync(OUT_DATA, head + "\n" + body);
console.log("logo-data.ts written:", MARKS.map(([n, , , r]) => `${n} ${r.toFixed(3)}`).join(", "));
